# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [3]:
# import NumPy into Python
import numpy as np


# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size=(1000,20))


# print the shape of X
print(X)


[[1732 2347  506 ... 2300 2011 3157]
 [2582 4596 1849 ... 1697 1948 2287]
 [1037 4031 4171 ... 2249 3543 4515]
 ...
 [3862  632 1506 ... 1986 4413 1385]
 [4807 4477 2796 ... 1243 4945 3603]
 [3587  145 4154 ...  152 2126 1851]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [5]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [17]:
# Print the shape of ave_cols
print(ave_cols.shape)


# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [11]:
# Mean normalize X
X_norm = np.divide(np.subtract(X, ave_cols), std_cols)


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [16]:
# Print the average of all the values of X_norm
print(X_norm)



# Print the average of the minimum value in each column of X_norm
print("Minimum value in each column", X_norm.max(axis=0))
 

# Print the average of the maximum value in each column of X_norm
print("Maximum value in each column", X_norm.min(axis=0))


[[-0.52948825 -0.13242848 -1.36602096 ... -0.1616183  -0.32549204
   0.42340398]
 [ 0.04950531  1.43054101 -0.41626428 ... -0.57691422 -0.36901921
  -0.17670821]
 [-1.00290063  1.03788749  1.22583178 ... -0.19674283  0.73297821
   1.36013082]
 ...
 [ 0.9214015  -1.32428827 -0.65883058 ... -0.37787521  1.3340677
  -0.79889349]
 [ 1.56510611  1.34784053  0.25344501 ... -0.88959141  1.70163048
   0.7310477 ]
 [ 0.73408005 -1.66273475  1.21380954 ... -1.64098088 -0.24603768
  -0.47745409]]
(1000, 20)
Minimum value in each column [1.69589053 1.69879633 1.80784946 1.7536504  1.73499922 1.73328726
 1.71120978 1.67972703 1.74952637 1.71960132 1.73122556 1.74259026
 1.72805336 1.71607065 1.75110718 1.74772804 1.71154031 1.68758493
 1.73341222 1.68915785]
Maximum value in each column [-1.69905525 -1.76280928 -1.72385929 -1.76247203 -1.75377837 -1.68656594
 -1.75682841 -1.76087191 -1.79955318 -1.76091996 -1.71078299 -1.70609348
 -1.73439401 -1.72935888 -1.69219113 -1.72986201 -1.71234755 -1.74497

You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [18]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([0, 2, 4, 1, 3])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [28]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row,col = X_norm.shape
row_indices = np.random.permutation(row)
print(row_indices)

[338 602 731 786 146 310 255 990 166   0 347  58 388 281 658 819 185 512
 193 320 453 636 668 923 948 880 825 531 716 515 107 571 983 204 544 738
 714  22 870 161 536 774 610 858 520 480 393 101 701 939 996 465 913 953
 270 835 287 585 803 732 791 875 873  17 333  29 587  99 485 829 394 429
 237 349 653 872  92 280 370  71 328 598 229 378 927 425 307 436 645 589
 976 886 212 226 390 475 561 832 198 574 734 267 615 600 809 787 908 140
 503 514 954 317 762 225  70 864 243 253 420 519 993 384 712 631 549 689
 887 322 230 897 316 554 105 368 141 110 363 881 398 279 160 481 609  86
 419 818 831 427 906 197 853 510 541 293 582 227 181 448 663 641 822 454
 241 125 426 497 214 375 681 866 729 670  47 486 311 926 557 811 792 203
 540 813 522 527 152 330 860 452 235 396 795 257 807 570 995 781 867 498
 228 259 234 899 493 389 513 507 116 551  65 376 655 456 650 940 713 438
 646 968 174 651 151 242 537 941 386   4 772 966 240 724 885 260  14 761
 113 935 231 812 710 608 893 854 937 399 296 836 50

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [30]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.



# Create a Training Set
X_train = X_norm[row_indices[0:600]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800]]

# Create a Test Set
X_test = X_norm[row_indices[800:1000]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [31]:
# Print the shape of X_train
print("X_train： ",X_train.shape)


# Print the shape of X_crossVal
print("X_crossVal： ",X_crossVal.shape)


# Print the shape of X_test
print("X_test: ",X_test.shape)


X_train：  (600, 20)
X_crossVal：  (200, 20)
X_test:  (200, 20)
